Create general discrete gibbs kernel
liesel-devs/liesel pull request #64
Opened 2023-04-05 13:18 UTC by jobrachem

Adds a function to create a general categorical/discrete Gibbs kernel. Note that I placed the function in `liesel/goose/gibbs.py`. If you think it fits better somewhere in `liesel/model`, I'd be thankful for a suggestion.

@hriebl since you provided one of the examples this function is based on, would you do the review?

Here's a screenshot of the documentation:

![image](https://user-images.githubusercontent.com/37882800/230091670-1611c431-1eee-426b-8fe9-21087774b02b.png)

Closes https://github.com/liesel-devs/liesel-internal/issues/149

2023-04-12 11:52 UTC, hriebl requested changes
Thanks, @jobrachem, this is a very cool feature! Just some suggestions...

2023-04-12 11:52 UTC, hriebl commented on liesel/goose/gibbs.py
> +            model.vars[name].value = value
How about using `model.auto_update = False` and `model.update("_model_log_prob")` here for better efficiency? This way, only the model log-prob node and its recursive inputs would be updated.

2023-04-12 11:52 UTC, hriebl commented on liesel/goose/gibbs.py
> +        draw = jnp.array(outcomes)[draw_index]
Maybe do the `jnp.array()` conversion outside of `transition_fn()`?

2023-04-13 11:38 UTC, jobrachem commented
@hriebl I implemented your suggestions. In one point I went a step further: I removed the `outcomes` argument altogether.

2023-04-13 12:58 UTC, hriebl commented on liesel/goose/gibbs.py
> +        List of possible outcomes.
Thank you! Not entirely sure about this change though. What if the prior is a `tfd.Bernoulli` distribution?

2023-04-13 13:01 UTC, jobrachem commented on liesel/goose/gibbs.py
> +        List of possible outcomes.
Maybe a `bernoulli_gibbs_kernel` function?

2023-04-13 13:21 UTC, hriebl commented on liesel/goose/gibbs.py
> +        List of possible outcomes.
Maybe, yes. But I think there are some more distributions that could be used with a finite Gibbs kernel: `tfd.Binomial`, `tfd.Categorical`, `tfd.Deterministic`, `tfd.Multinomial`, `tfd.OneHotCategorical`, etc. Also, users might want to implement their own distributions. For this reason, I think having an `outcomes` argument is a good idea, but an automatic "outcomes extractor" for the most common distributions would of course be very handy... :slightly_smiling_face:

2023-04-13 13:43 UTC, jobrachem commented
@hriebl the `outcomes` argument is back, including a new test and a new example in the docstring.

2023-04-14 12:54 UTC, jobrachem commented
@hriebl I merged your changes. Now the ball is back in your court I guess :D

2023-04-16 14:41 UTC, hriebl approved these changes
I've updated the docstring a little bit. This is now ready to be merged. Thank you again, @jobrachem!

2023-04-16 14:44 UTC, merged